apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: clean
      image: alpine
      script: |
        rm -rf /workspace/source/*
  workspaces:
    - name: source
